apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.0.2
    helm.sh/chart: grafana-9.2.10
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: kube-prometheus-stack
spec:
  type: NodePort
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
      nodePort: 30002
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
